# Manual
This is manually constructing a single hidden layer of three neurons without matrix multiplication.

In [58]:
import numpy as np
from scipy.special import expit as sigmoid

inputs = np.array([
    0,
    0,
    255,
    0
])

weights = np.random.rand(3, 4)
biases = np.random.rand(3)

a0 = sigmoid(inputs[0] * weights[0][0] + inputs[1] * weights[0][1] + inputs[2] * weights[0][2] + inputs[3] * weights[0][3] + biases[0])
a1 = sigmoid(inputs[0] * weights[1][0] + inputs[1] * weights[1][1] + inputs[2] * weights[1][2] + inputs[3] * weights[1][3] + biases[1])
a2 = sigmoid(inputs[0] * weights[2][0] + inputs[1] * weights[2][1] + inputs[2] * weights[2][2] + inputs[3] * weights[2][3] + biases[2])

np.array([a0, a1, a2])

array([1., 1., 1.])

In [57]:
weights

array([[0.59448098, 0.98074841, 0.51766438, 0.32840577],
       [0.7621153 , 0.13155814, 0.8727305 , 0.98895314],
       [0.28482493, 0.56133138, 0.55928762, 0.06858993]])

In [56]:
biases

array([0.9815132 , 0.91947162, 0.10841519])

# Matrix

This is constructing a single hidden layer of three neurons with matrix multiplication.

In [51]:
l_weights = weights

In [52]:
l_inputs = inputs
l_inputs

array([12,  6, -4,  0])

In [53]:
l_biases = biases

In [55]:
sigmoid(np.add(np.dot(l_weights, l_inputs), l_biases))

array([0.9999934 , 0.99936629, 0.99059582])