In [32]:
import numpy as np
from scipy.special import expit as sigmoid

In [44]:
inputs = [
    12,
    6,
    -4
]

weights = np.random.rand(3, 3)
biases = np.random.rand(3)

In [59]:
weights

array([[0.18687967, 0.86820965, 0.80847648],
       [0.40218924, 0.37560453, 0.74364933],
       [0.83335946, 0.92994301, 0.63097784]])

In [60]:
biases

array([0.38648158, 0.60212638, 0.7169843 ])

# Manual
This is manually constructing a single hidden layer of three neurons without matrix multiplication.

In [61]:
a0 = sigmoid(inputs[0] * weights[0][0] + inputs[1] * weights[0][1] + inputs[2] * weights[0][2] + biases[0])
a1 = sigmoid(inputs[0] * weights[1][0] + inputs[1] * weights[1][1] + inputs[2] * weights[1][2] + biases[1])
a2 = sigmoid(inputs[0] * weights[2][0] + inputs[1] * weights[2][1] + inputs[2] * weights[2][2] + biases[2])

np.array([a0, a1, a2])

array([0.99009135, 0.9910528 , 0.99999896])

# Matrix

This is constructing a single hidden layer of three neurons with matrix multiplication.

In [62]:
l_weights = np.array(weights)

In [63]:
l_inputs = np.array(inputs)
l_inputs

array([12,  6, -4])

In [64]:
l_biases = np.array(biases)

In [65]:
sigmoid(np.add(np.dot(l_weights, l_inputs), l_biases))

array([0.99009135, 0.9910528 , 0.99999896])