In [1]:
import numpy as np
from scipy.special import expit as sigmoid

In [15]:
neurons_in_hidden_layer = 3

inputs = np.array([
    12,
    6,
    -4,
    0
])

weights = np.random.rand(neurons_in_hidden_layer, inputs.size)
biases = np.random.rand(neurons_in_hidden_layer)

In [16]:
weights

array([[0.46907989, 0.79267596, 0.31179914, 0.86566805],
       [0.34890068, 0.94693257, 0.75124973, 0.17137959],
       [0.92505593, 0.35516196, 0.94855155, 0.57324634]])

In [17]:
biases

array([0.96799244, 0.09283868, 0.22042352])

# Manual
This is manually constructing a single hidden layer of three neurons without matrix multiplication.

In [18]:
a0 = sigmoid(inputs[0] * weights[0][0] + inputs[1] * weights[0][1] + inputs[2] * weights[0][2] + inputs[3] * weights[0][3] + biases[0])
a1 = sigmoid(inputs[0] * weights[1][0] + inputs[1] * weights[1][1] + inputs[2] * weights[1][2] + inputs[3] * weights[1][3] + biases[1])
a2 = sigmoid(inputs[0] * weights[2][0] + inputs[1] * weights[2][1] + inputs[2] * weights[2][2] + inputs[3] * weights[2][3] + biases[2])

np.array([a0, a1, a2])

array([0.99995916, 0.99904824, 0.99993608])

# Matrix

This is constructing a single hidden layer of three neurons with matrix multiplication.

In [23]:
l_weights = weights

In [24]:
l_inputs = inputs
l_inputs

array([12,  6, -4,  0])

In [25]:
l_biases = biases

In [26]:
sigmoid(np.add(np.dot(l_weights, l_inputs), l_biases))

array([0.99995916, 0.99904824, 0.99993608])