In [1]:
import numpy as np
from scipy.special import expit

In [205]:
inputs = [
    12,
    6,
    -4
]

weights = [
    [1.45, 1.45, 1.45],
    [-0.414, -0.414, -0.414],
    [5.23, 5.23, 5.23]
]

biases = [
    -1,
    -1,
    2
]

a0 = inputs[0] * weights[0][0] + inputs[1] * weights[0][1] + inputs[2] * weights[0][2] + biases[0]
a1 = inputs[0] * weights[1][0] + inputs[1] * weights[1][1] + inputs[2] * weights[1][2] + biases[1]
a2 = inputs[0] * weights[2][0] + inputs[1] * weights[2][1] + inputs[2] * weights[2][2] + biases[2]

print([a0, a1, a2])

[19.299999999999997, -6.796, 75.22000000000001]


In [216]:
l_inputs = np.array(inputs)
l_inputs

array([12,  6, -4])

In [217]:
l_weights = np.array(weights)
l_weights

array([[ 1.45 ,  1.45 ,  1.45 ],
       [-0.414, -0.414, -0.414],
       [ 5.23 ,  5.23 ,  5.23 ]])

In [218]:
l_biases = np.array(biases)
l_biases

array([-1, -1,  2])

In [219]:
np.add(np.dot(l_weights, l_inputs), l_biases)

array([19.3  , -6.796, 75.22 ])