Single hidden layer with 2 outputs

In [92]:
import cv2
import numpy as np
from scipy.special import expit as sigmoid

In [93]:
inputs = np.ndarray.flatten(cv2.bitwise_not(cv2.imread('2.png',cv2.IMREAD_GRAYSCALE)))
training_output = [1, 0]

In [94]:
layer1_weights = np.random.rand(10, inputs.shape[0])
layer1_biases = np.random.rand(10)

In [95]:
layer1_weights

array([[0.61567501, 0.36728525, 0.71523829, ..., 0.74351983, 0.87589598,
        0.41154832],
       [0.61781065, 0.2062637 , 0.36579137, ..., 0.6635571 , 0.68775684,
        0.75086666],
       [0.27111431, 0.8192178 , 0.86362043, ..., 0.58693243, 0.1298015 ,
        0.17746978],
       ...,
       [0.94002887, 0.42342587, 0.72488849, ..., 0.67590475, 0.51050169,
        0.86962121],
       [0.81566614, 0.91425128, 0.36420069, ..., 0.5530282 , 0.39911924,
        0.01480422],
       [0.48253461, 0.90922098, 0.78971871, ..., 0.2820059 , 0.23594412,
        0.9319933 ]])

In [96]:
layer1_biases

array([0.71989823, 0.92608875, 0.34598535, 0.85202944, 0.34483113,
       0.09432388, 0.22428814, 0.25318009, 0.2055813 , 0.86390021])

In [97]:
layer1 = sigmoid(np.add(np.dot(layer1_weights, inputs), layer1_biases))
layer1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [98]:
output_weights = np.random.rand(2, layer1.shape[0])
output_biases = np.random.rand(2)
output_weights

array([[0.72526207, 0.953747  , 0.61280603, 0.35118269, 0.90487891,
        0.10392804, 0.28267184, 0.40621033, 0.99221809, 0.30445483],
       [0.34763538, 0.55514676, 0.39346843, 0.3488914 , 0.9957498 ,
        0.72143666, 0.54444321, 0.52819894, 0.90583924, 0.63118954]])

In [99]:
output_biases

array([0.86508058, 0.83312104])

In [108]:
output = sigmoid(np.add(np.dot(output_weights, layer1), output_biases))
output

array([0.99850247, 0.99889314])

In [110]:
mean = output.mean()
mean

0.9986978055296143

In [113]:
cost = np.sum((output - mean)**2)
cost

7.631090894847716e-08