Single hidden layer with 2 outputs

In [2]:
import cv2
import numpy as np
from scipy.special import expit as sigmoid

In [3]:
inputs_a = np.ndarray.flatten(cv2.bitwise_not(cv2.imread('2a.png',cv2.IMREAD_GRAYSCALE)))
inputs_b = np.ndarray.flatten(cv2.bitwise_not(cv2.imread('2b.png',cv2.IMREAD_GRAYSCALE)))
y = [[1], [0]]

inputs_a = inputs_a[:, np.newaxis]
inputs_a.shape

(1482, 1)

In [8]:
layer1_weights = np.random.rand(10, inputs_a.shape[0])
layer1_biases = np.random.rand(10)[:, np.newaxis]

In [9]:
layer1_weights.shape

(10, 1482)

In [10]:
layer1 = sigmoid(np.add(np.dot(layer1_weights, inputs_a), layer1_biases))
layer1

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [11]:
output_weights = np.random.rand(2, layer1.shape[0])
output_biases = np.random.rand(2)[:, np.newaxis]
output_weights

array([[0.40292783, 0.63381389, 0.29588163, 0.79022421, 0.03057389,
        0.42282361, 0.56708132, 0.01829036, 0.28368031, 0.81103553],
       [0.51079704, 0.52703752, 0.17797813, 0.16836748, 0.90523596,
        0.7142708 , 0.30397768, 0.07130499, 0.23826369, 0.09394393]])

In [20]:
output_weights.T

array([[0.40292783, 0.51079704],
       [0.63381389, 0.52703752],
       [0.29588163, 0.17797813],
       [0.79022421, 0.16836748],
       [0.03057389, 0.90523596],
       [0.42282361, 0.7142708 ],
       [0.56708132, 0.30397768],
       [0.01829036, 0.07130499],
       [0.28368031, 0.23826369],
       [0.81103553, 0.09394393]])

In [13]:
output = sigmoid(np.add(np.dot(output_weights, layer1), output_biases))
layer1.shape

(10, 1)

In [14]:
output

array([[0.98839032],
       [0.98863563]])

In [21]:
d_output = np.dot(output_weights.T, 2 * (y - output) * (output - (1 - output)))

In [22]:
d_output

array([[-0.97789016],
       [-1.00403558],
       [-0.33720188],
       [-0.30741914],
       [-1.74852154],
       [-1.37061744],
       [-0.57452379],
       [-0.13736998],
       [-0.45397024],
       [-0.16313624]])

In [ ]:
y