Single hidden layer with 2 outputs

In [1]:
import cv2
import numpy as np
from scipy.special import expit as sigmoid

In [2]:
inputs = np.array([
    [74, 200],
    [72, 240],
    [55, 180]
])

y = [[1], [1]]

In [3]:
layer1_weights = np.random.randn(inputs.shape[1],6)
layer1_biases = np.random.randn(1, layer1_weights.shape[1])

In [4]:
inputs

array([[ 74, 200],
       [ 72, 240],
       [ 55, 180]])

In [5]:
layer1_weights

array([[ 0.08748914, -0.23230143,  0.06197947, -0.01094023,  1.79959805,
         0.86066793],
       [-0.83796475,  1.21613859,  0.18644666, -0.50603462, -1.90054158,
        -0.48451687]])

In [6]:
layer1_biases

array([[-0.3176554 , -1.44900018, -0.08968063, -0.28508482, -0.62952177,
        -0.24006215]])

In [7]:
layer1 = np.add(np.dot(inputs,layer1_weights), layer1_biases)
# layer1_a = sigmoid(layer1)
layer1

array([[-161.43641007,  224.58841163,   41.78613229, -102.30158621,
        -247.56758091,  -33.45400912],
       [-195.12997853,  273.69855806,   49.12003977, -122.52109063,
        -327.18844003,  -54.5560197 ],
       [-146.33940861,  204.67936707,   36.87958914,  -91.9730294 ,
        -243.74911241,  -40.11636238]])

In [8]:
output = np.zeros((inputs.shape[1], 2))
output_weights = np.random.randn(layer1.shape[1],2 )
output_biases = np.random.randn(inputs.shape[0], 2)
output_biases

array([[ 0.19743777, -1.08997293],
       [ 0.19652395, -2.0143955 ],
       [ 0.9376813 ,  0.00683356]])

In [9]:
output_weights

array([[ 0.25598652, -1.57537788],
       [-0.50972296, -0.3346207 ],
       [ 1.14782895,  0.3144768 ],
       [ 0.56993119,  1.25748487],
       [ 0.08141321,  0.33317884],
       [-1.00591547,  3.03325655]])

In [10]:
output = np.add(np.dot(layer1_a, output_weights), output_biases)
output_a = sigmoid(output)

delta_output = (output_a - y) * (1 - output) * output_error
delta_output

NameError: name 'layer1_a' is not defined

In [ ]:
layer1_a