Single hidden layer with 2 outputs

In [3]:
import cv2
import numpy as np
from scipy.special import expit as sigmoid

In [375]:
class Network:
    def __init__(self, inputs, expected_outcome):
        self.inputs = np.array(inputs)
        self.hidden_layer1 = np.zeros((4, 1))
        self.hidden_layer1_activation = np.zeros((4, 1))
        self.output = np.zeros((2, 1))
        self.output_activation = np.zeros((2, 1))
        self.y = expected_outcome

        self.hidden_layer1_weights = np.random.rand(self.inputs.shape[0], 4)
        self.hidden_layer1_biases = np.random.rand(4, 1)
        self.output_weights = np.random.rand(self.hidden_layer1.shape[0], 2)
        self.output_biases = np.random.rand(2, 1)
        
    def feedforward(self):
        self.hidden_layer_1 = np.add(np.dot(self.inputs, self.hidden_layer1_weights), self.hidden_layer1_biases)
        self.hidden_layer1_activation = sigmoid(self.hidden_layer1)
        self.output = np.add(np.dot(self.output_weights, self.hidden_layer1_activation), self.output_biases)
        self.output_activation = sigmoid(self.output)

    def cost(self):
        return np.sum((self.y - self.output_activation)**2)
    
    def backpropagate(self):
        dC_dY = (-2 * (self.y - self.output_activation))
        dO_dW = self.output * (1 - self.output)
        return [
            dC_dY,
            self.hidden_layer1_activation,
            dC_dY * dO_dW
        ]
        

In [376]:
nn = Network([[85,8], [93,9]], [[0], [1]])
nn.hidden_layer1_weights

array([[0.70559071, 0.91669899, 0.63684929, 0.80752454],
       [0.76438029, 0.89212752, 0.92091341, 0.27510642]])

In [377]:
nn.feedforward()
nn.output
nn.hidden_layer1_activation
nn.backpropagate()

ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [310]:
inputs = np.array()
# inputs = np.array([[23, 4, 2, 5]])

inputs
layer1_weights = np.random.rand(4, inputs.shape[0])
layer1_weights

TypeError: array() missing required argument 'object' (pos 1)

In [3]:
inputs_a = np.ndarray.flatten(cv2.bitwise_not(cv2.imread('2a.png',cv2.IMREAD_GRAYSCALE)))
inputs_b = np.ndarray.flatten(cv2.bitwise_not(cv2.imread('2b.png',cv2.IMREAD_GRAYSCALE)))
y = [[1], [0]]

inputs_a = inputs_a[:, np.newaxis]
inputs_a.shape

(1482, 1)

In [8]:
layer1_weights = np.random.rand(10, inputs_a.shape[0])
layer1_biases = np.random.rand(10)[:, np.newaxis]

In [9]:
layer1_weights.shape

(10, 1482)

In [10]:
layer1 = sigmoid(np.add(np.dot(layer1_weights, inputs_a), layer1_biases))
layer1

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [11]:
output_weights = np.random.rand(2, layer1.shape[0])
output_biases = np.random.rand(2)[:, np.newaxis]
output_weights

array([[0.40292783, 0.63381389, 0.29588163, 0.79022421, 0.03057389,
        0.42282361, 0.56708132, 0.01829036, 0.28368031, 0.81103553],
       [0.51079704, 0.52703752, 0.17797813, 0.16836748, 0.90523596,
        0.7142708 , 0.30397768, 0.07130499, 0.23826369, 0.09394393]])

In [36]:
output_weights

array([[0.40292783, 0.63381389, 0.29588163, 0.79022421, 0.03057389,
        0.42282361, 0.56708132, 0.01829036, 0.28368031, 0.81103553],
       [0.51079704, 0.52703752, 0.17797813, 0.16836748, 0.90523596,
        0.7142708 , 0.30397768, 0.07130499, 0.23826369, 0.09394393]])

In [13]:
output = sigmoid(np.add(np.dot(output_weights, layer1), output_biases))
layer1.shape

(10, 1)

In [26]:
output

array([[0.98839032],
       [0.98863563]])

In [61]:
(2 * (y - output) * output * (1 - output))

array([[ 0.00026644],
       [-0.02221507]])

In [59]:
weights_n + output_weights

array([[0.40319426, 0.63408033, 0.29614807, 0.79049065, 0.03084032,
        0.42309005, 0.56734776, 0.0185568 , 0.28394675, 0.81130197],
       [0.48858197, 0.50482245, 0.15576305, 0.14615241, 0.88302089,
        0.69205572, 0.28176261, 0.04908992, 0.21604862, 0.07172885]])